/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubRouteImport } from './routes/hub'
import { Route as KrishnaRouteImport } from './routes/krishna'
import { Route as RamaRouteImport } from './routes/rama'
import { Route as ShivaRouteImport } from './routes/shiva'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const KrishnaRoute = KrishnaRouteImport.update({
  id: '/krishna',
  path: '/krishna',
  getParentRoute: () => rootRouteImport,
} as any)
const RamaRoute = RamaRouteImport.update({
  id: '/rama',
  path: '/rama',
  getParentRoute: () => rootRouteImport,
} as any)
const ShivaRoute = ShivaRouteImport.update({
  id: '/shiva',
  path: '/shiva',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hub': typeof HubRoute
  '/krishna': typeof KrishnaRoute
  '/rama': typeof RamaRoute
  '/shiva': typeof ShivaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hub': typeof HubRoute
  '/krishna': typeof KrishnaRoute
  '/rama': typeof RamaRoute
  '/shiva': typeof ShivaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hub': typeof HubRoute
  '/krishna': typeof KrishnaRoute
  '/rama': typeof RamaRoute
  '/shiva': typeof ShivaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hub' | '/krishna' | '/rama' | '/shiva' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hub' | '/krishna' | '/rama' | '/shiva' | '/sitemap.xml'
  id:
    '__root__' | '/' | '/hub' | '/krishna' | '/rama' | '/shiva' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HubRoute: typeof HubRoute
  KrishnaRoute: typeof KrishnaRoute
  RamaRoute: typeof RamaRoute
  ShivaRoute: typeof ShivaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/krishna': {
      id: '/krishna'
      path: '/krishna'
      fullPath: '/krishna'
      preLoaderRoute: typeof KrishnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rama': {
      id: '/rama'
      path: '/rama'
      fullPath: '/rama'
      preLoaderRoute: typeof RamaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shiva': {
      id: '/shiva'
      path: '/shiva'
      fullPath: '/shiva'
      preLoaderRoute: typeof ShivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HubRoute: HubRoute,
  KrishnaRoute: KrishnaRoute,
  RamaRoute: RamaRoute,
  ShivaRoute: ShivaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
